### PR TITLE
deps: upgrade egg

### PR DESCRIPTION
**Pull request by popomore**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

### CODE REVIEW

**Comment by shaoshuai0102** [comment]
unit tests failed

**Comment by popomore** [comment]
https://github.com/node-modules/ready-callback/pull/99

**Comment by popomore** [comment]
It may break some test, I will release a major version.

**Comment by popomore** [comment]
+ egg-mock@3.0.0

**Pull request merged**
