### PR TITLE
feat: try to lookup egg that will be the default customEgg

### PR DESCRIPTION
**Pull request by popomore**
##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] commit message follows commit guidelines

### CODE REVIEW

**Comment by atian25** [comment]
```
Test Framework

customEgg is optional that is process.cwd() by default.
```

这里的描述有点不准确

**Comment by atian25** [comment]
rebase 下

**Comment by popomore** [comment]
改了

**Comment by fengmk2** [comment]
+1

**Comment by fengmk2** [comment]
1.2.0

**Pull request merged**
